#define DAY_BRIGHTNESS      0
#define DAY_CONTRAST        0
#define DAY_SATURATION      0
#define DAY_TINT_R          0
#define DAY_TINT_G          0
#define DAY_TINT_B          0

#define NIGHT_BRIGHTNESS   -15
#define NIGHT_CONTRAST       0
#define NIGHT_SATURATION   -10
#define NIGHT_TINT_R         0
#define NIGHT_TINT_G         0
#define NIGHT_TINT_B        25

#define CLEAR_BRIGHTNESS     5
#define CLEAR_CONTRAST       0
#define CLEAR_SATURATION     0
#define CLEAR_TINT_R         0
#define CLEAR_TINT_G         0
#define CLEAR_TINT_B         0

#define SUNNY_BRIGHTNESS    10
#define SUNNY_CONTRAST       5
#define SUNNY_SATURATION     0
#define SUNNY_TINT_R         0
#define SUNNY_TINT_G         0
#define SUNNY_TINT_B         0

#define EXTREMESUN_BRIGHTNESS   20
#define EXTREMESUN_CONTRAST     10
#define EXTREMESUN_SATURATION    5
#define EXTREMESUN_TINT_R        0
#define EXTREMESUN_TINT_G        0
#define EXTREMESUN_TINT_B        0

#define OVERCAST_BRIGHTNESS   -5
#define OVERCAST_CONTRAST     -5
#define OVERCAST_SATURATION   -5
#define OVERCAST_TINT_R        0
#define OVERCAST_TINT_G        0
#define OVERCAST_TINT_B        0

#define RAIN_BRIGHTNESS      -12
#define RAIN_CONTRAST         -5
#define RAIN_SATURATION       -5
#define RAIN_TINT_R            0
#define RAIN_TINT_G            0
#define RAIN_TINT_B            0

#define HEAVYRAIN_BRIGHTNESS   -20
#define HEAVYRAIN_CONTRAST     -10
#define HEAVYRAIN_SATURATION   -10
#define HEAVYRAIN_TINT_R         0
#define HEAVYRAIN_TINT_G         0
#define HEAVYRAIN_TINT_B         0

#define HAIL_BRIGHTNESS        5
#define HAIL_CONTRAST          0
#define HAIL_SATURATION       -5
#define HAIL_TINT_R            0
#define HAIL_TINT_G            0
#define HAIL_TINT_B           10

#define BLIZZARD_BRIGHTNESS   -10
#define BLIZZARD_CONTRAST      -5
#define BLIZZARD_SATURATION   -10
#define BLIZZARD_TINT_R         0
#define BLIZZARD_TINT_G         0
#define BLIZZARD_TINT_B        20

#define FOG_BRIGHTNESS       10
#define FOG_CONTRAST        -10
#define FOG_SATURATION      -20
#define FOG_TINT_R           15
#define FOG_TINT_G           15
#define FOG_TINT_B           15

#define BLIZZARDOVERLAY_BRIGHTNESS    0
#define BLIZZARDOVERLAY_CONTRAST      0
#define BLIZZARDOVERLAY_SATURATION   -10
#define BLIZZARDOVERLAY_TINT_R         5
#define BLIZZARDOVERLAY_TINT_G         5
#define BLIZZARDOVERLAY_TINT_B        20
